### ISSUE TITLE
Cloudformation supports this now!

### ISSUE THREAD

**Issue by matthiasfeist** [Jimdo/serverless-dynamodb-ttl#16]
I checked today and Cloudformation supports TTL now :)

**Comment by HenrikFricke** [comment]
@matthiasfeist Thanks for the hint, we will mark this plugin as `DEPRECATED` now.

**Comment by benswinburne** [comment]
@HenrikFricke - if I wasn't to use this plugin, how can I have serverless configure TTL for me?

**Comment by sbstjn** [comment]
If you create your DynamoDB table within your `serverless.yml`, you can just use [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-timetolivespecification.html):

```yaml
    DynamoDBTableIdentifier:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: my-table-name
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expiredAt
          Enabled: true
```
